// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_netbird

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func NetbirdProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{}
}

type NetbirdModel struct {
}
