// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_group

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
)

func GroupResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The unique identifier of a group",
				MarkdownDescription: "The unique identifier of a group",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Group name identifier",
				MarkdownDescription: "Group name identifier",
			},
			"peers": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "List of peers ids",
				MarkdownDescription: "List of peers ids",
				Validators: []validator.List{listvalidator.SizeAtLeast(1)},
			},
		},
	}
}

type GroupModel struct {
	Id    types.String `tfsdk:"id"`
	Name  types.String `tfsdk:"name"`
	Peers types.List   `tfsdk:"peers"`
}
